// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: local_pose.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "local_pose.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gazebo {
namespace msgs {

namespace {

const ::google::protobuf::Descriptor* LocalPose_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LocalPose_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_local_5fpose_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_local_5fpose_2eproto() {
  protobuf_AddDesc_local_5fpose_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "local_pose.proto");
  GOOGLE_CHECK(file != NULL);
  LocalPose_descriptor_ = file->message_type(0);
  static const int LocalPose_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalPose, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalPose, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalPose, position_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalPose, orientation_),
  };
  LocalPose_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LocalPose_descriptor_,
      LocalPose::default_instance_,
      LocalPose_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalPose, _has_bits_[0]),
      -1,
      -1,
      sizeof(LocalPose),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LocalPose, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_local_5fpose_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LocalPose_descriptor_, &LocalPose::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_local_5fpose_2eproto() {
  delete LocalPose::default_instance_;
  delete LocalPose_reflection_;
}

void protobuf_AddDesc_local_5fpose_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_local_5fpose_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::gazebo::msgs::protobuf_AddDesc_local_5fvector3d_2eproto();
  ::gazebo::msgs::protobuf_AddDesc_local_5fquaternion_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020local_pose.proto\022\013gazebo.msgs\032\024local_v"
    "ector3d.proto\032\026local_quaternion.proto\"\206\001"
    "\n\tLocalPose\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\t \001(\r\022,\n"
    "\010position\030\003 \002(\0132\032.gazebo.msgs.LocalVecto"
    "r3d\0221\n\013orientation\030\004 \002(\0132\034.gazebo.msgs.L"
    "ocalQuaternion", 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "local_pose.proto", &protobuf_RegisterTypes);
  LocalPose::default_instance_ = new LocalPose();
  LocalPose::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_local_5fpose_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_local_5fpose_2eproto {
  StaticDescriptorInitializer_local_5fpose_2eproto() {
    protobuf_AddDesc_local_5fpose_2eproto();
  }
} static_descriptor_initializer_local_5fpose_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LocalPose::kNameFieldNumber;
const int LocalPose::kIdFieldNumber;
const int LocalPose::kPositionFieldNumber;
const int LocalPose::kOrientationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LocalPose::LocalPose()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gazebo.msgs.LocalPose)
}

void LocalPose::InitAsDefaultInstance() {
  position_ = const_cast< ::gazebo::msgs::LocalVector3d*>(&::gazebo::msgs::LocalVector3d::default_instance());
  orientation_ = const_cast< ::gazebo::msgs::LocalQuaternion*>(&::gazebo::msgs::LocalQuaternion::default_instance());
}

LocalPose::LocalPose(const LocalPose& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gazebo.msgs.LocalPose)
}

void LocalPose::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0u;
  position_ = NULL;
  orientation_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

LocalPose::~LocalPose() {
  // @@protoc_insertion_point(destructor:gazebo.msgs.LocalPose)
  SharedDtor();
}

void LocalPose::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete position_;
    delete orientation_;
  }
}

void LocalPose::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LocalPose::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LocalPose_descriptor_;
}

const LocalPose& LocalPose::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_local_5fpose_2eproto();
  return *default_instance_;
}

LocalPose* LocalPose::default_instance_ = NULL;

LocalPose* LocalPose::New(::google::protobuf::Arena* arena) const {
  LocalPose* n = new LocalPose;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LocalPose::Clear() {
// @@protoc_insertion_point(message_clear_start:gazebo.msgs.LocalPose)
  if (_has_bits_[0 / 32] & 15u) {
    if (has_name()) {
      name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    id_ = 0u;
    if (has_position()) {
      if (position_ != NULL) position_->::gazebo::msgs::LocalVector3d::Clear();
    }
    if (has_orientation()) {
      if (orientation_ != NULL) orientation_->::gazebo::msgs::LocalQuaternion::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool LocalPose::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gazebo.msgs.LocalPose)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "gazebo.msgs.LocalPose.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_position;
        break;
      }

      // required .gazebo.msgs.LocalVector3d position = 3;
      case 3: {
        if (tag == 26) {
         parse_position:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_orientation;
        break;
      }

      // required .gazebo.msgs.LocalQuaternion orientation = 4;
      case 4: {
        if (tag == 34) {
         parse_orientation:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_orientation()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_id;
        break;
      }

      // optional uint32 id = 9;
      case 9: {
        if (tag == 72) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gazebo.msgs.LocalPose)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gazebo.msgs.LocalPose)
  return false;
#undef DO_
}

void LocalPose::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gazebo.msgs.LocalPose)
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "gazebo.msgs.LocalPose.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // required .gazebo.msgs.LocalVector3d position = 3;
  if (has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->position_, output);
  }

  // required .gazebo.msgs.LocalQuaternion orientation = 4;
  if (has_orientation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *this->orientation_, output);
  }

  // optional uint32 id = 9;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gazebo.msgs.LocalPose)
}

::google::protobuf::uint8* LocalPose::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gazebo.msgs.LocalPose)
  // optional string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "gazebo.msgs.LocalPose.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required .gazebo.msgs.LocalVector3d position = 3;
  if (has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->position_, false, target);
  }

  // required .gazebo.msgs.LocalQuaternion orientation = 4;
  if (has_orientation()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *this->orientation_, false, target);
  }

  // optional uint32 id = 9;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gazebo.msgs.LocalPose)
  return target;
}

int LocalPose::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:gazebo.msgs.LocalPose)
  int total_size = 0;

  if (has_position()) {
    // required .gazebo.msgs.LocalVector3d position = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->position_);
  }

  if (has_orientation()) {
    // required .gazebo.msgs.LocalQuaternion orientation = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->orientation_);
  }

  return total_size;
}
int LocalPose::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:gazebo.msgs.LocalPose)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000c) ^ 0x0000000c) == 0) {  // All required fields are present.
    // required .gazebo.msgs.LocalVector3d position = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->position_);

    // required .gazebo.msgs.LocalQuaternion orientation = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->orientation_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional uint32 id = 9;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LocalPose::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gazebo.msgs.LocalPose)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const LocalPose* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LocalPose>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gazebo.msgs.LocalPose)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gazebo.msgs.LocalPose)
    MergeFrom(*source);
  }
}

void LocalPose::MergeFrom(const LocalPose& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gazebo.msgs.LocalPose)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_position()) {
      mutable_position()->::gazebo::msgs::LocalVector3d::MergeFrom(from.position());
    }
    if (from.has_orientation()) {
      mutable_orientation()->::gazebo::msgs::LocalQuaternion::MergeFrom(from.orientation());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void LocalPose::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gazebo.msgs.LocalPose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LocalPose::CopyFrom(const LocalPose& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gazebo.msgs.LocalPose)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LocalPose::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000c) != 0x0000000c) return false;

  if (has_position()) {
    if (!this->position_->IsInitialized()) return false;
  }
  if (has_orientation()) {
    if (!this->orientation_->IsInitialized()) return false;
  }
  return true;
}

void LocalPose::Swap(LocalPose* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LocalPose::InternalSwap(LocalPose* other) {
  name_.Swap(&other->name_);
  std::swap(id_, other->id_);
  std::swap(position_, other->position_);
  std::swap(orientation_, other->orientation_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LocalPose::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LocalPose_descriptor_;
  metadata.reflection = LocalPose_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LocalPose

// optional string name = 1;
bool LocalPose::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void LocalPose::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
void LocalPose::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void LocalPose::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
 const ::std::string& LocalPose::name() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LocalPose.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LocalPose::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gazebo.msgs.LocalPose.name)
}
 void LocalPose::set_name(const char* value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gazebo.msgs.LocalPose.name)
}
 void LocalPose::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gazebo.msgs.LocalPose.name)
}
 ::std::string* LocalPose::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.LocalPose.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LocalPose::release_name() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.LocalPose.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LocalPose::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.LocalPose.name)
}

// optional uint32 id = 9;
bool LocalPose::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void LocalPose::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
void LocalPose::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
void LocalPose::clear_id() {
  id_ = 0u;
  clear_has_id();
}
 ::google::protobuf::uint32 LocalPose::id() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LocalPose.id)
  return id_;
}
 void LocalPose::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:gazebo.msgs.LocalPose.id)
}

// required .gazebo.msgs.LocalVector3d position = 3;
bool LocalPose::has_position() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void LocalPose::set_has_position() {
  _has_bits_[0] |= 0x00000004u;
}
void LocalPose::clear_has_position() {
  _has_bits_[0] &= ~0x00000004u;
}
void LocalPose::clear_position() {
  if (position_ != NULL) position_->::gazebo::msgs::LocalVector3d::Clear();
  clear_has_position();
}
const ::gazebo::msgs::LocalVector3d& LocalPose::position() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LocalPose.position)
  return position_ != NULL ? *position_ : *default_instance_->position_;
}
::gazebo::msgs::LocalVector3d* LocalPose::mutable_position() {
  set_has_position();
  if (position_ == NULL) {
    position_ = new ::gazebo::msgs::LocalVector3d;
  }
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.LocalPose.position)
  return position_;
}
::gazebo::msgs::LocalVector3d* LocalPose::release_position() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.LocalPose.position)
  clear_has_position();
  ::gazebo::msgs::LocalVector3d* temp = position_;
  position_ = NULL;
  return temp;
}
void LocalPose::set_allocated_position(::gazebo::msgs::LocalVector3d* position) {
  delete position_;
  position_ = position;
  if (position) {
    set_has_position();
  } else {
    clear_has_position();
  }
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.LocalPose.position)
}

// required .gazebo.msgs.LocalQuaternion orientation = 4;
bool LocalPose::has_orientation() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void LocalPose::set_has_orientation() {
  _has_bits_[0] |= 0x00000008u;
}
void LocalPose::clear_has_orientation() {
  _has_bits_[0] &= ~0x00000008u;
}
void LocalPose::clear_orientation() {
  if (orientation_ != NULL) orientation_->::gazebo::msgs::LocalQuaternion::Clear();
  clear_has_orientation();
}
const ::gazebo::msgs::LocalQuaternion& LocalPose::orientation() const {
  // @@protoc_insertion_point(field_get:gazebo.msgs.LocalPose.orientation)
  return orientation_ != NULL ? *orientation_ : *default_instance_->orientation_;
}
::gazebo::msgs::LocalQuaternion* LocalPose::mutable_orientation() {
  set_has_orientation();
  if (orientation_ == NULL) {
    orientation_ = new ::gazebo::msgs::LocalQuaternion;
  }
  // @@protoc_insertion_point(field_mutable:gazebo.msgs.LocalPose.orientation)
  return orientation_;
}
::gazebo::msgs::LocalQuaternion* LocalPose::release_orientation() {
  // @@protoc_insertion_point(field_release:gazebo.msgs.LocalPose.orientation)
  clear_has_orientation();
  ::gazebo::msgs::LocalQuaternion* temp = orientation_;
  orientation_ = NULL;
  return temp;
}
void LocalPose::set_allocated_orientation(::gazebo::msgs::LocalQuaternion* orientation) {
  delete orientation_;
  orientation_ = orientation;
  if (orientation) {
    set_has_orientation();
  } else {
    clear_has_orientation();
  }
  // @@protoc_insertion_point(field_set_allocated:gazebo.msgs.LocalPose.orientation)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace msgs
}  // namespace gazebo

// @@protoc_insertion_point(global_scope)
